language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t nakul/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nakul/docker-react npm run test