language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t nakul/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nakul/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "docker-react"
    env: "dockerreact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-668098664718"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY